# Generated by Django 3.1.1 on 2021-07-07 21:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='url',
            field=models.CharField(default=uuid.UUID('96c12cbe-6471-463d-8f1b-f24bc63f1682'), max_length=200),
        ),
    ]
