# Generated by Django 3.1.1 on 2021-08-02 14:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_auto_20210707_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='url',
            field=models.CharField(default=uuid.UUID('cfbe814a-bd6c-44f0-b256-88a420374570'), max_length=200),
        ),
    ]
