# Generated by Django 3.1.1 on 2021-06-11 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20210611_1515'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='city_link',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='country_link',
            new_name='country',
        ),
    ]
