# Generated by Django 3.1.1 on 2021-06-11 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20210611_2009'),
        ('blog', '0020_auto_20210611_2109'),
    ]

    operations = [
    ]
