# Generated by Django 3.1.1 on 2021-06-15 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_merge_20210611_2111'),
        ('blog', '0021_auto_20210615_1646'),
    ]

    operations = [
    ]
