# Generated by Django 3.1.1 on 2021-06-16 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_article_caption'),
        ('blog', '0022_merge_20210615_1725'),
    ]

    operations = [
    ]
