# Generated by Django 3.1.1 on 2021-06-17 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_merge_20210616_2108'),
        ('blog', '0023_delete_comment'),
    ]

    operations = [
    ]
