# Generated by Django 3.1.1 on 2021-06-07 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210607_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(choices=[('Sev', 'Sev'), ('Amby', 'Amby')], default='Amby', max_length=200),
        ),
    ]
