# Generated by Django 3.1.1 on 2021-06-07 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210607_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(choices=[('Amby', 'Amby'), ('Sev', 'Sev')], default='Amby', max_length=200),
        ),
    ]
