# Generated by Django 3.1.1 on 2021-06-07 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210607_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paragraph',
            name='titel',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
