# Generated by Django 3.1.1 on 2021-06-09 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210607_0140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='position',
            new_name='google_map',
        ),
    ]
