# Generated by Django 3.1.1 on 2021-06-10 16:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20210609_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='publish_on',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
