# Generated by Django 3.1.1 on 2021-06-10 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_article_publish_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='stars',
            new_name='snacks',
        ),
    ]
