# Generated by Django 3.1.1 on 2021-06-16 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20210615_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='caption',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
