# Generated by Django 3.1.1 on 2021-06-23 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_delete_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='sent_newsletter',
            field=models.BooleanField(default=False),
        ),
    ]
