# Generated by Django 3.1.1 on 2021-07-07 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_merge_20210617_1928'),
        ('blog', '0024_article_sent_newsletter'),
    ]

    operations = [
    ]
