# Generated by Django 3.1.1 on 2022-06-20 18:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_auto_20210802_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='url',
            field=models.CharField(default=uuid.UUID('3ba5d11e-1d52-48a4-b1b3-b281c1d37b3f'), max_length=200),
        ),
    ]
