# Generated by Django 4.0.5 on 2022-06-28 18:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0008_auto_20220620_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='url',
            field=models.CharField(default=uuid.UUID('f07a8b5e-6235-4569-964a-4755eb08c323'), max_length=200),
        ),
    ]
