# Generated by Django 4.0.5 on 2022-07-02 19:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0011_alter_subscription_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='url',
            field=models.CharField(default=uuid.UUID('9c0de4f9-764d-4df9-b313-b9ccdfc954ea'), max_length=200),
        ),
    ]
